module.exports = {
  someSidebar: {
  	'System Requirements': ['system-requirements/index',  		
  	   {Hardware: ['system-requirements/hardware/index', 
  				   'system-requirements/hardware/solaris'],
  		Software: ['system-requirements/software/index',
  				   'system-requirements/software/git', 
  				   'system-requirements/software/java',
  				   'system-requirements/software/perl',  				   
  				   {PostgreSQL: ['system-requirements/software/postgres/index',
  				   				 'system-requirements/software/postgres/postgres',
  				   				 'system-requirements/software/postgres/hikari']},
  				   'system-requirements/software/tomcat',
  				   'system-requirements/software/macs',
  				   'system-requirements/software/maven',
  				   'system-requirements/software/intellij',
  				   'system-requirements/software/solr',	
  				   {Gradle: ['system-requirements/software/gradle/index',
  				   			 'system-requirements/software/gradle/faqs']}]}],

  	'Get started': ['get-started/index',
  					'get-started/tutorial/index',
  					'get-started/tutorial/webapp',
  					'get-started/tutorial/test-data',
  					'get-started/quick-start',
  					'get-started/create-your-mine',
  					'get-started/testmine',
  					'get-started/intermine-tests'],

  	InterMine: ['intermine/index',
  				'intermine/intermine',
  				'intermine/upgrade',
  				'intermine/roadmap',
  				'intermine/intermine-versions',
  				'intermine/get-involved',
  				'intermine/https',
  				'intermine/amazon'],

  	'Data Model': ['data-model/index',
  				   'data-model/overview',
  				   'data-model/model',
  				   'data-model/data-labels',
  				   'data-model/overlaps',
  				   'data-model/model-ontologies'],

  	Database: ['database/index',
  			   'database/download-scripts',
  			   {'Data Sources': ['database/data-sources/index',
  			   					 'database/data-sources/library/index']}],

  	'Guide to Customising your Web Application': ['webapp/blue-genes/index',
  												  'webapp/homepage/index',
  												  {'Report Page': ['webapp/report-page/index',
  												  				   'webapp/report-page/report-page',
  												  				   'webapp/report-page/report-displayers',
  												  				   'webapp/report-page/report-displayers-examples',
  												  				   'webapp/report-page/webapp-tables']},
  												  {Lists: ['webapp/lists/index',
  												  		   'webapp/lists/lists-page',
  												  		   'webapp/lists/list-upload',
  												  		   'webapp/lists/list-upgrade',
  												  		   'webapp/lists/list-analysis/index',
  												  		   {'List Widgets': ['embedding/list-widgets/index',
  												  		   					 'embedding/list-widgets/q-and-a',
  												  		   					 'embedding/list-widgets/enrichment-widgets']}]},
  												  'webapp/template-queries/index',
  												  'webapp/query-results/index',
  												  'webapp/query-builder/index',
  												  'webapp/keyword-search/index',
  												  'webapp/layout/index',
  												  'webapp/region-search/index',
  												  {'Customise Web Application': ['webapp/properties/index',
  												  								 'webapp/properties/intermine-properties',
  												  								 'webapp/properties/model-properties',
  												  								 'webapp/properties/web-properties',
  												  								 'webapp/properties/webconfig-model',
  												  								 'webapp/properties/class-keys',
  												  								 'webapp/properties/javascript-options']},
  												  'webapp/data-categories/index',
  												  'webapp/markup/index',
  												  'webapp/help/index',
  												  'webapp/linking-in/index',
  												  {'Third party tools': ['webapp/third-party-tools/index',
  												  						 'webapp/third-party-tools/cytoscape',
  												  						 'webapp/third-party-tools/esyn',
  												  						 'webapp/third-party-tools/galaxy',
  												  						 'webapp/third-party-tools/gbrowse',
  												  						 'webapp/third-party-tools/heatmap',
  												  						 'webapp/third-party-tools/jbrowse']},


  												  {'Monitoring Site Usage': ['webapp/monitoring-site-usage/index',
  												  							 'webapp/monitoring-site-usage/google-analytics',
  												  							 'webapp/monitoring-site-usage/trackers',
  												  							 'webapp/monitoring-site-usage/search-engines']},
  												  'webapp/admin/index',
  												  {'User Accounts': ['webapp/user-accounts/index',
  												  					 'webapp/user-accounts/userprofile',
  												  					 'webapp/user-accounts/open-id']},
  												  'webapp/performance/index',

  												  'webapp/diagnostic/index',
  												  'webapp/javadoc/index',
  												  'webapp/permanent-url/index',
  												  'webapp/iodocs',
  												  'webapp/frictionless/index'],

  	'Web Services': ['web-services/index'],
  	'Embedding InterMine Components': ['embedding/index',
  									   {'List Widgets': ['embedding/list-widgets/index',
  												  		 'embedding/list-widgets/q-and-a',
  												  		 'embedding/list-widgets/enrichment-widgets']},
  									   {'Apps/C Grunt Build': ['embedding/apps-c/index',
  									   						  'embedding/apps-c/usage',
  									   						  'embedding/apps-c/publication-search',
  									   						  'embedding/apps-c/elastic-med']},
  									   'embedding/api-loader',
  									   'embedding/imjs',
  									   'embedding/examples'],

  	About: ['about/contact-us', 'about/index', 'about/intermine', 'about/privacy-policy', 'about/services'],
    Description: ['doc1'],
  },
};
